% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Proyecto 1},
  pdfauthor={Bryan Martínez, Adriana Palacios, Brandon Rivera, Javier Benítez, y Pedro Avila},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Proyecto 1}
\author{Bryan Martínez, Adriana Palacios, Brandon Rivera, Javier
Benítez, y Pedro Avila}
\date{2026-02-16}

\begin{document}
\maketitle

\subsection{\texorpdfstring{\textbf{Situación
Problemática}}{Situación Problemática}}\label{situaciuxf3n-problemuxe1tica}

En los últimos años se ha vuelto común escuchar que el matrimonio y la
formación de una familia ya no forman parte de los planes de muchas
personas, o que estas decisiones se están postergando a edades más
avanzadas. Asimismo, se percibe que las relaciones de pareja tienden a
adoptar formas distintas a las tradicionales, ahora vemos a más personas
que buscan convivir con una pareja sin matrimonio o bajo compromisos
legales.

Sin embargo, estas percepciones sociales no siempre son evidentes o
respaldadas con información verídica. En particular, no se conoce con
certeza si en Guatemala ha ocurrido una disminución en los matrimonios,
un aumento en los divorcios, o cambios significativos en la edad a la
que las personas deciden casarse o divorciarse. Tampoco es claro si
estos posibles cambios se presentan de manera uniforme en todo el país o
si existen departamentos en donde se identifiquen diferencias
relevantes.

Al tener acceso a datos oficiales por parte de la INE sobre matrimonios
y divorcios en Guatemala, surge la necesidad de analizar estos datos
para tratar de responder a estas interrogantes, buscando identificar
diferentes patrones a lo largo de la última década y media. Por medio de
nuestro análisis seremos capaces de contrastar las percepciones sociales
con datos reales, y comprender si realmente ha ocurrido un cambio en la
dinámica de los matrimonios y divorcios guatemaltecos.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{\texorpdfstring{\textbf{Problema
Científico}}{Problema Científico}}\label{problema-cientuxedfico}

No se cuenta con evidencia estadística concluyente sobre si, en
Guatemala (2009--2022), han ocurrido cambios significativos en los
matrimonios y divorcios, ni si estos cambios se relacionan con la edad
de las personas o presentan diferencias relevantes entre departamentos.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{\texorpdfstring{\textbf{Objetivos}}{Objetivos}}\label{objetivos}

\textbf{Objetivo General}

Analizar los datos de matrimonios y divorcios en Guatemala con el fin de
identificar patrones demográficos y diferencias entre departamentos, y
evaluar si se han producido cambios en la dinámica de estos eventos a lo
largo del período analizado.

\textbf{Objetivos Específicos}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Examinar la distribución de los matrimonios y divorcios según los
  rangos de edad de las personas, con el propósito de identificar
  posibles variaciones en las edades en las que ocurren estos eventos.
\item
  Analizar la distribución de matrimonios y divorcios por departamento,
  con el fin de detectar la existencia de patrones regionales
  relevantes.
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{\texorpdfstring{\textbf{Descripción de los
Datos}}{Descripción de los Datos}}\label{descripciuxf3n-de-los-datos}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Algunos departamentos vienen escritos diferente, mayúsculas, minúsculas o con/sin tildes.}
\NormalTok{norm\_depto }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x) \{}
\NormalTok{  x }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{str\_trim}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{str\_squish}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{stri\_trans\_general}\NormalTok{(}\StringTok{"Latin{-}ASCII"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}  \CommentTok{\# quita tildes (Petén {-}\textgreater{} Peten)}
    \FunctionTok{str\_to\_lower}\NormalTok{()}
\NormalTok{\}}

\CommentTok{\# Carga de datos}
\NormalTok{matrimonios\_depto }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"matrimonios\_depto\_mes.csv"}\NormalTok{, }\AttributeTok{show\_col\_types =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{departamento =} \FunctionTok{norm\_depto}\NormalTok{(departamento))}

\NormalTok{matrimonios\_edad  }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"matrimonios\_edad.csv"}\NormalTok{, }\AttributeTok{show\_col\_types =} \ConstantTok{FALSE}\NormalTok{)}

\NormalTok{divorcios\_depto }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"divorcios\_depto\_mes.csv"}\NormalTok{, }\AttributeTok{show\_col\_types =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{departamento =} \FunctionTok{norm\_depto}\NormalTok{(departamento))}

\NormalTok{divorcios\_edad  }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}\StringTok{"divorcios\_edad.csv"}\NormalTok{, }\AttributeTok{show\_col\_types =} \ConstantTok{FALSE}\NormalTok{)}

\CommentTok{\# Limpieza de datasets}
\NormalTok{matrimonios\_depto\_limpio }\OtherTok{\textless{}{-}}\NormalTok{ matrimonios\_depto }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(nivel\_geo }\SpecialCharTok{==} \StringTok{"departamento"}\NormalTok{, }\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(mes))}

\NormalTok{divorcios\_depto\_limpio }\OtherTok{\textless{}{-}}\NormalTok{ divorcios\_depto }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(nivel\_geo }\SpecialCharTok{==} \StringTok{"departamento"}\NormalTok{, }\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(mes))}

\NormalTok{matrimonios\_edad\_limpio }\OtherTok{\textless{}{-}}\NormalTok{ matrimonios\_edad }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}
    \SpecialCharTok{!}\FunctionTok{str\_detect}\NormalTok{(}\FunctionTok{tolower}\NormalTok{(edad\_hombre\_grupo), }\StringTok{"ignorado"}\NormalTok{),}
    \SpecialCharTok{!}\FunctionTok{str\_detect}\NormalTok{(}\FunctionTok{tolower}\NormalTok{(edad\_mujer\_grupo), }\StringTok{"ignorado"}\NormalTok{)}
\NormalTok{  )}

\NormalTok{divorcios\_edad\_limpio }\OtherTok{\textless{}{-}}\NormalTok{ divorcios\_edad }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}
    \SpecialCharTok{!}\FunctionTok{str\_detect}\NormalTok{(}\FunctionTok{tolower}\NormalTok{(edad\_hombre\_grupo), }\StringTok{"ignorado"}\NormalTok{),}
    \SpecialCharTok{!}\FunctionTok{str\_detect}\NormalTok{(}\FunctionTok{tolower}\NormalTok{(edad\_mujer\_grupo), }\StringTok{"ignorado"}\NormalTok{)}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\subsubsection{\texorpdfstring{\textbf{Significado y tipo de cada
variable}}{Significado y tipo de cada variable}}\label{significado-y-tipo-de-cada-variable}

Para el análisis de los datos, se estará trabajando con cuatro datasets
con información desde 2009 hasta 2022:

\begin{itemize}
\tightlist
\item
  matrimonios\_depto\_mes: matrimonios registrados en cada mes acorde a
  cada departamento.
\item
  matrimonios\_edad: matrimonios que ocurrieron en diferentes rangos de
  edad.
\item
  divorcios\_depto: divorcios almacenados por mes para cada
  departamento.
\item
  divorcios\_edad: divorcios acontecidos en diferentes rangos de edad.
\end{itemize}

\paragraph{\texorpdfstring{\textbf{Variables Compartidas en Todos los
Datasets}}{Variables Compartidas en Todos los Datasets}}\label{variables-compartidas-en-todos-los-datasets}

\textbf{anio}

\begin{itemize}
\tightlist
\item
  Representa el año en que fue registrada la observación.
\item
  La variable es cuantitativa discreta.
\end{itemize}

\textbf{valor}

\begin{itemize}
\tightlist
\item
  Número de veces que ocurrió un evento, dependiendo del dataset, este
  puede representar cantidad de matrimonios o divorcios.
\item
  La variable es cuantitativa discreta.
\end{itemize}

\paragraph{\texorpdfstring{\textbf{Variables Compartidas en Datasets con
Datos
Departamentales}}{Variables Compartidas en Datasets con Datos Departamentales}}\label{variables-compartidas-en-datasets-con-datos-departamentales}

\textbf{nivel\_geo}

\begin{itemize}
\tightlist
\item
  Se utiliza para indicar si la observación es de un departamento en
  específico, o si se tiene registrada a nivel nacional.
\item
  La variable es cualitativa nominal.
\end{itemize}

\textbf{departamento}

\begin{itemize}
\tightlist
\item
  Es el departamento en donde se registró la observación; este valor
  puede estar vacío cuando el registro corresponde al total nacional.
\item
  La variable es cualitativa nominal.
\end{itemize}

\textbf{mes}

\begin{itemize}
\tightlist
\item
  Muestra el número de mes al que corresponden los datos de la
  observación.
\item
  La variable es cualitativa ordinal; aunque se representa como un
  número en el dataset, se utiliza para indicar la posición del mes
  dentro del año y no como una magnitud numérica.
\end{itemize}

\paragraph{\texorpdfstring{\textbf{Variables Compartidas en Datasets con
Datos de
Edades}}{Variables Compartidas en Datasets con Datos de Edades}}\label{variables-compartidas-en-datasets-con-datos-de-edades}

\textbf{edad\_mujer\_grupo}

\begin{itemize}
\tightlist
\item
  Rango de edad al que pertenece la novia/mujer de la observación.
\item
  La variable es cualitativa ordinal.
\end{itemize}

\textbf{edad\_hombre\_grupo}

\begin{itemize}
\tightlist
\item
  Rango de edad al que pertence el novio/hombre de la observación.
\item
  La variable es cualitativa ordinal.
\end{itemize}

\subsubsection{\texorpdfstring{\textbf{Cantidad de Variables y
Observaciones}}{Cantidad de Variables y Observaciones}}\label{cantidad-de-variables-y-observaciones}

\textbf{Matrimonios por departamento:}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dim}\NormalTok{(matrimonios\_depto)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4186    5
\end{verbatim}

Se tienen 4186 observaciones y 5 variables.

\textbf{Matrimonios por rangos de edad:}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dim}\NormalTok{(matrimonios\_edad)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2191    4
\end{verbatim}

Hay 2191 observaciones y 4 variables.

\textbf{Divorcios por departamento:}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dim}\NormalTok{(divorcios\_depto)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4186    5
\end{verbatim}

Se tienen 4186 observaciones y 5 variables.

\textbf{Divorcios por rangos de edad:}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{dim}\NormalTok{(divorcios\_edad)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1878    4
\end{verbatim}

Hay 1878 observaciones y 4 variables.

\subsubsection{\texorpdfstring{\textbf{Operaciones de Limpieza
Realizadas}}{Operaciones de Limpieza Realizadas}}\label{operaciones-de-limpieza-realizadas}

Al explorar las opciones de descarga de datos disponibles en la
plataforma del INE, se observó que gran parte de la información se
ofrece en formato .sav, lo cual requiere software de IBM o procesos
adicionales para manipularlos. Para facilitar el análisis, se decidió
utilizar los libros de Excel disponibles para las estadísticas de
matrimonios y divorcios.

Los archivos descargados contenían múltiples hojas y tablas cruzadas que
no se encontraban en un formato que se pudiera utilizar directamente
para análisis en R. Por esta razón, se realizó un proceso de limpieza.
Primero, se seleccionaron únicamente las hojas asociadas a rangos de
edad y distribución por departamento en todos los libros de matrimonios
y divorcios.

Después, se transformaron las tablas cruzadas a un formato que
permitiera el análisis estadístico. La idea era que en cada observación
se pudiera identificar sencillamente los datos para un año determinado,
logrando reconocer el departamento, rangos de edad de los novios, y la
cantidad de un evento (matrimonio o divorcio). Asimismo, se
estandarizaron varios datos, pues en varias ocasiones se redactaba de
forma distinta, por ejemplo, había matrimonios o divorcios que ocurrían
después de los 65 años, y en algunos documentos aparecía como 65 y mas,
y en otros correctamente escrito como 65 y más. También, se normalizaron
los nombres de los departamentos para evitar inconsistencias causadas
por mayúsculas, espacios y tildes.

Adicionalmente, al analizar datos estadísticos sobre los valores de
algunos datasets, se decidió dejar una versión limpia para trabajar
únicamente con datos relevantes para los análisis en donde
explícitamente se conservaran datos a nivel geográfico de departamento
en los datasets de departamento. En los datasets por rangos de edad, se
eliminaron los registros clasificados como Ignorado, ya que no aportan
información útil para el análisis demográfico.

Finalmente, los datos procesados fueron exportados a archivos CSV para
facilitar su manipulación y análisis en R.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{\texorpdfstring{\textbf{Análisis
Exploratorio}}{Análisis Exploratorio}}\label{anuxe1lisis-exploratorio}

\subsubsection{\texorpdfstring{\textbf{Exploración de Variables
Cuantitativas}}{Exploración de Variables Cuantitativas}}\label{exploraciuxf3n-de-variables-cuantitativas}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\paragraph{\texorpdfstring{\textbf{Estadística
Descriptiva}}{Estadística Descriptiva}}\label{estaduxedstica-descriptiva}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(matrimonios\_depto\_limpio }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{pull}\NormalTok{(valor))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     8.0   135.0   204.0   285.7   355.0  2619.0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(divorcios\_depto\_limpio }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{pull}\NormalTok{(valor))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.00    8.00   13.00   22.34   19.00  410.00
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(matrimonios\_edad\_limpio }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{pull}\NormalTok{(valor))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##     0.0     5.0    62.0   566.7   282.0 14859.0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(divorcios\_edad\_limpio }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{pull}\NormalTok{(valor))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.00    0.00    2.00   24.10   15.25  767.00
\end{verbatim}

Para el análisis de variables numéricas se decidió enfocar el estudio
únicamente en la variable \textbf{valor}, ya que esta representa la
cantidad de eventos registrados (matrimonios o divorcios) y es la única
variable cuantitativa con significado estadístico. Las demás variables
numéricas presentes en los datasets, como el año o el mes, cumplen una
función temporal, pero no representan magnitudes susceptibles de
análisis de tendencia central o dispersión en este contexto.

Adicionalmente, para evitar distorsiones en las medidas estadísticas, se
trabajó únicamente con registros a nivel departamental y se excluyeron
los totales nacionales. En el caso de los datasets por rangos de edad,
se eliminaron los registros clasificados como \emph{Ignorado}, ya que no
aportan información útil para el análisis demográfico.

Bajo estos criterios, se obtuvieron los siguientes resultados
descriptivos para la variable \textbf{valor}:

\textbf{Matrimonios por departamento (mensuales)}

\begin{itemize}
\tightlist
\item
  Los valores presentan un \textbf{mínimo de 8} y un \textbf{máximo de
  2619 matrimonios}, con una \textbf{mediana de 204}. La \textbf{media
  (285.7)} es considerablemente mayor que la mediana, lo que indica una
  distribución asimétrica hacia la derecha, con la presencia de valores
  extremos altos. Esto sugiere que existen algunos departamentos con
  cantidades de matrimonios significativamente mayores al resto,
  mientras que la mayoría presenta valores más moderados. El máximo de
  matrimonios mensuales se dio en enero del 2012 en Guatemala.
\end{itemize}

\textbf{Divorcios por departamento (mensuales)}

\begin{itemize}
\tightlist
\item
  Los valores oscilan entre \textbf{0 y 410 divorcios}, con una
  \textbf{mediana de 13} y una \textbf{media de 22.34}. Nuevamente, la
  media supera a la mediana, evidenciando una \textbf{asimetría
  positiva}. Como dato curioso se buscó en el dataset quien era el 410,
  y fue Guatemala en junio del 2019. En comparación con los matrimonios,
  los divorcios ocurren en cantidades considerablemente menores, lo cual
  es coherente con la naturaleza del fenómeno.
\end{itemize}

\textbf{Matrimonios por rangos de edad}

\begin{itemize}
\tightlist
\item
  Se observa una gran dispersión en los valores, con un \textbf{máximo
  de 14,859 registros}, una \textbf{mediana de 62} y una \textbf{media
  de 566.7}. La diferencia marcada entre la mediana y la media confirma
  la presencia de \textbf{grupos de edad con una concentración muy alta
  de matrimonios}, mientras que otros rangos presentan valores bajos.
  Esto indica que los matrimonios no se distribuyen uniformemente entre
  los rangos establecidos por el INE, sino que se concentran en edades
  específicas. El tope de matrimonios se dio en parejas en donde tanto
  el novio y la novia estaban entre 20 y 24 años durante el 2021, cuando
  estuvimos en cuarentena por la mayor parte del tiempo.
\end{itemize}

\textbf{Divorcios por rangos de edad}

\begin{itemize}
\tightlist
\item
  Los valores son más bajos en comparación con los matrimonios, con una
  \textbf{mediana de 2} y una \textbf{media de 24.1}, y un máximo de
  \textbf{767 divorcios}. La fuerte diferencia entre la media y la
  mediana refleja una \textbf{distribución altamente sesgada}, donde
  pocos rangos de edad concentran la mayor cantidad de divorcios. Es
  interesante ver que los 767 divorcios, se dieron con el hombre y mujer
  estando entre 30 y 34 años, en el año 2022, justo en el año en que
  estábamos empezando a salir de las restricciones por COVID.
\end{itemize}

\paragraph{\texorpdfstring{\textbf{Distribuciones por
variables}}{Distribuciones por variables}}\label{distribuciones-por-variables}

\subparagraph{\texorpdfstring{\textbf{Gráficamente}}{Gráficamente}}\label{gruxe1ficamente}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{each\_df }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{(}
  \AttributeTok{matrimonios\_depto =}\NormalTok{ matrimonios\_depto\_limpio,}
  \AttributeTok{divorcios\_depto =}\NormalTok{ divorcios\_depto\_limpio,}
  \AttributeTok{matrimonios\_edad =}\NormalTok{ matrimonios\_edad\_limpio,}
  \AttributeTok{divorcios\_edad =}\NormalTok{ divorcios\_edad\_limpio}
\NormalTok{)}

\NormalTok{plot\_valor\_hist\_box }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(df, df\_name, }\AttributeTok{bins =} \DecValTok{30}\NormalTok{) \{}
\NormalTok{  df }\OtherTok{\textless{}{-}} \FunctionTok{as.data.frame}\NormalTok{(df)}

\NormalTok{  p\_hist }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ valor)) }\SpecialCharTok{+}
    \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{bins =}\NormalTok{ bins) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}
      \AttributeTok{title =} \FunctionTok{paste}\NormalTok{(}\StringTok{"Histograma de valor {-}"}\NormalTok{, df\_name),}
      \AttributeTok{x =} \StringTok{"valor"}\NormalTok{,}
      \AttributeTok{y =} \StringTok{"Frecuencia"}
\NormalTok{    ) }\SpecialCharTok{+}
    \FunctionTok{theme\_minimal}\NormalTok{()}

\NormalTok{  p\_box }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(df, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ valor)) }\SpecialCharTok{+}
    \FunctionTok{geom\_boxplot}\NormalTok{() }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}
      \AttributeTok{title =} \FunctionTok{paste}\NormalTok{(}\StringTok{"Boxplot de valor {-}"}\NormalTok{, df\_name),}
      \AttributeTok{y =} \StringTok{"valor"}
\NormalTok{    ) }\SpecialCharTok{+}
    \FunctionTok{theme\_minimal}\NormalTok{()}

  \FunctionTok{print}\NormalTok{(p\_hist)}
  \FunctionTok{print}\NormalTok{(p\_box)}
\NormalTok{\}}

\ControlFlowTok{for}\NormalTok{ (df\_name }\ControlFlowTok{in} \FunctionTok{names}\NormalTok{(each\_df)) \{}
  \FunctionTok{plot\_valor\_hist\_box}\NormalTok{(each\_df[[df\_name]], df\_name)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-7-1.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-7-2.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-7-3.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-7-4.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-7-5.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-7-6.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-7-7.pdf}}
\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-7-8.pdf}}

\textbf{Distribución de los datos (histogramas)}

Luego de obtener medidas de tendencia central y dispersión para la
variable valor en cada dataset, se generaron histogramas con el fin de
comprender visualmente la forma de distribución de los datos. En los
cuatro casos se observa una concentración fuerte hacia valores bajos,
con una cola hacia la derecha. La mayoría de observaciones registran
cantidades moderadas, mientras que un subconjunto reducido presenta
valores mucho más altos. Por ejemplo, en matrimonios por departamento
(mensual) una parte considerable de los datos se concentra
aproximadamente entre 0 y 800, mientras que en divorcios por
departamento (mensual) la mayor densidad se ubica entre 0 y 100. En los
datasets por rangos de edad, la concentración hacia valores bajos
también es evidente, lo cual sugiere que los conteos altos se concentran
en grupos específicos de edad, mientras que muchos rangos (por ejemplo,
edades muy bajas o muy altas) presentan valores pequeños o incluso
cercanos a cero.

\textbf{Valores atípicos (boxplots)}

Los diagramas de cajas y bigotes refuerzan lo observado en los
histogramas: en los cuatro datasets se identifican múltiples valores
atípicos, lo cual indica la presencia de meses, departamentos o
combinaciones de rangos de edad con conteos significativamente mayores
al resto. En matrimonios por departamento (mensual) destacan varios
puntos por encima de 800 y algunos cercanos al máximo del dataset; en
divorcios por departamento (mensual) también se observan atípicos por
encima de 120 y hasta valores cercanos a 400. En los datasets por edad,
los outliers son todavía más notorios debido a la concentración en
ciertos rangos; por ejemplo, en matrimonios por rangos de edad aparece
un valor extremo cercano a 15,000, correspondiente a una combinación de
edades altamente frecuente. En conjunto, estos resultados sugieren que
los eventos no se distribuyen uniformemente entre departamentos o rangos
de edad, sino que existen picos de alta concentración asociados a rangos
bastatne comunes.

\subparagraph{\texorpdfstring{\textbf{Prueba de
Normalidad}}{Prueba de Normalidad}}\label{prueba-de-normalidad}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{prueba\_lilliefors\_valor }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(df, df\_name, }\AttributeTok{alpha =} \FloatTok{0.05}\NormalTok{) \{}
\NormalTok{  x }\OtherTok{\textless{}{-}} \FunctionTok{na.omit}\NormalTok{(df}\SpecialCharTok{$}\NormalTok{valor)}
\NormalTok{  test }\OtherTok{\textless{}{-}} \FunctionTok{lillie.test}\NormalTok{(x)}

\NormalTok{  decision }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(}
\NormalTok{    test}\SpecialCharTok{$}\NormalTok{p.value }\SpecialCharTok{\textless{}}\NormalTok{ alpha,}
    \StringTok{"Se rechaza normalidad"}\NormalTok{,}
    \StringTok{"No se rechaza normalidad"}
\NormalTok{  )}

  \FunctionTok{tibble}\NormalTok{(}
    \AttributeTok{dataset =}\NormalTok{ df\_name,}
    \AttributeTok{n =} \FunctionTok{length}\NormalTok{(x),}
    \AttributeTok{p\_value =}\NormalTok{ test}\SpecialCharTok{$}\NormalTok{p.value,}
    \AttributeTok{conclusion =}\NormalTok{ decision}
\NormalTok{  )}
\NormalTok{\}}

\NormalTok{resultados\_normalidad }\OtherTok{\textless{}{-}} \FunctionTok{bind\_rows}\NormalTok{(}
  \FunctionTok{lapply}\NormalTok{(}\FunctionTok{names}\NormalTok{(each\_df), }\ControlFlowTok{function}\NormalTok{(nm) \{}
    \FunctionTok{prueba\_lilliefors\_valor}\NormalTok{(each\_df[[nm]], nm)}
\NormalTok{  \})}
\NormalTok{)}

\NormalTok{resultados\_normalidad}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4 x 4
##   dataset               n   p_value conclusion           
##   <chr>             <int>     <dbl> <chr>                
## 1 matrimonios_depto  3696 7.41e-323 Se rechaza normalidad
## 2 divorcios_depto    3696 0         Se rechaza normalidad
## 3 matrimonios_edad   1855 0         Se rechaza normalidad
## 4 divorcios_edad     1568 0         Se rechaza normalidad
\end{verbatim}

Para corroborar lo observado gráficamente (asimetría positiva y
presencia de valores atípicos), se aplicó la prueba de normalidad de
Lilliefors sobre la variable valor en cada dataset. En todos los casos
se obtuvo un p-value \textless{} 0.05, por lo que se rechaza la
hipótesis de normalidad.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection{\texorpdfstring{\textbf{Exploración de Variables
Categóricas}}{Exploración de Variables Categóricas}}\label{exploraciuxf3n-de-variables-categuxf3ricas}

En esta sección se analizan las variables categóricas mediante tablas de
frecuencia y proporciones. En nuestros datasets, la variable valor
representa el conteo de eventos (matrimonios o divorcios) asociado a una
categoría específica: ya sea un departamento (en los datasets
geográficos) o un rango de edad (en los datasets demográficos). Por lo
tanto, tanto los totales como las proporciones describen la
concentración relativa de eventos en cada categoría. Es decir, una
proporción alta indica que una categoría (por ejemplo, un departamento o
un rango de edad) concentra una parte mayor de los registros totales del
periodo analizado.

\paragraph{\texorpdfstring{\textbf{Análisis de Datasets de
Departamentos}}{Análisis de Datasets de Departamentos}}\label{anuxe1lisis-de-datasets-de-departamentos}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{matr\_depto\_cat }\OtherTok{\textless{}{-}}\NormalTok{ matrimonios\_depto }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(nivel\_geo }\SpecialCharTok{==} \StringTok{"departamento"}\NormalTok{, }\FunctionTok{is.na}\NormalTok{(mes))}

\NormalTok{div\_depto\_cat }\OtherTok{\textless{}{-}}\NormalTok{ divorcios\_depto }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(nivel\_geo }\SpecialCharTok{==} \StringTok{"departamento"}\NormalTok{, }\FunctionTok{is.na}\NormalTok{(mes))}

\NormalTok{tabla\_depto\_matr }\OtherTok{\textless{}{-}}\NormalTok{ matr\_depto\_cat }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(departamento) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total =} \FunctionTok{sum}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{prop =}\NormalTok{ total }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(total)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(total))}

\NormalTok{tabla\_depto\_div }\OtherTok{\textless{}{-}}\NormalTok{ div\_depto\_cat }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(departamento) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total =} \FunctionTok{sum}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{prop =}\NormalTok{ total }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(total)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(total))}

\NormalTok{tabla\_depto\_matr}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 22 x 3
##    departamento    total   prop
##    <chr>           <dbl>  <dbl>
##  1 guatemala      213948 0.203 
##  2 huehuetenango   78339 0.0742
##  3 alta verapaz    77626 0.0735
##  4 san marcos      69837 0.0661
##  5 quiche          68741 0.0651
##  6 quetzaltenango  64494 0.0611
##  7 chimaltenango   53487 0.0507
##  8 escuintla       50966 0.0483
##  9 suchitepequez   47873 0.0453
## 10 totonicapan     37006 0.0350
## # i 12 more rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tabla\_depto\_div}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 22 x 3
##    departamento   total   prop
##    <chr>          <dbl>  <dbl>
##  1 guatemala      31813 0.385 
##  2 quetzaltenango  6423 0.0778
##  3 escuintla       3768 0.0456
##  4 san marcos      3155 0.0382
##  5 jutiapa         3145 0.0381
##  6 suchitepequez   2826 0.0342
##  7 huehuetenango   2683 0.0325
##  8 izabal          2597 0.0315
##  9 retalhuleu      2436 0.0295
## 10 santa rosa      2295 0.0278
## # i 12 more rows
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(tabla\_depto\_matr, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{reorder}\NormalTok{(departamento, prop), }\AttributeTok{y =}\NormalTok{ prop)) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{coord\_flip}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{labels =}\NormalTok{ scales}\SpecialCharTok{::}\NormalTok{percent) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Proporción de matrimonios por departamento (2009{-}2022)"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Departamento"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Proporción"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-10-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(tabla\_depto\_div, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{reorder}\NormalTok{(departamento, prop), }\AttributeTok{y =}\NormalTok{ prop)) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{coord\_flip}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{labels =}\NormalTok{ scales}\SpecialCharTok{::}\NormalTok{percent) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Proporción de divorcios por departamento (2009{-}2022)"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Departamento"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Proporción"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-10-2.pdf}}

Al analizar la distribución de matrimonios por departamento
(2009--2022), se observa una marcada concentración en pocos
departamentos. Los tres departamentos con mayor presencia son Guatemala
(20.26\%), Huehuetenango (7.42\%) y Alta Verapaz (7.35\%). La diferencia
entre Guatemala y el resto es notable: incluso sumando Huehuetenango y
Alta Verapaz, no se alcanza la proporción que aporta Guatemala por sí
sola. Esto sugiere que Guatemala concentra una fracción muy importante
de los matrimonios registrados durante el periodo.

En el caso de divorcios por departamento, la concentración es todavía
más marcada en Guatemala. Guatemala registra 31,813 divorcios, lo que
corresponde al 38.53\% del total, seguido por Quetzaltenango con 6,423
(7.78\%) y Escuintla con 3,768 (4.56\%). Nuevamente, Guatemala sobresale
ampliamente y domina la distribución. Esta diferencia también se aprecia
claramente en los gráficos: la barra de Guatemala es muy superior a las
demás.

\paragraph{\texorpdfstring{\textbf{Análisis de Datasets de Rangos de
Edad}}{Análisis de Datasets de Rangos de Edad}}\label{anuxe1lisis-de-datasets-de-rangos-de-edad}

Para el análisis por edades, se construyeron cuatro tablas:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  matrimonios por rango de edad de mujeres,
\item
  divorcios por rango de edad de mujeres,
\item
  matrimonios por rango de edad de hombres,
\item
  divorcios por rango de edad de hombres.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{matr\_edad\_cat }\OtherTok{\textless{}{-}}\NormalTok{ matrimonios\_edad }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(edad\_mujer\_grupo }\SpecialCharTok{!=} \StringTok{"Ignorado"}\NormalTok{, edad\_hombre\_grupo }\SpecialCharTok{!=} \StringTok{"Ignorado"}\NormalTok{)}

\NormalTok{div\_edad\_cat }\OtherTok{\textless{}{-}}\NormalTok{ divorcios\_edad }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(edad\_mujer\_grupo }\SpecialCharTok{!=} \StringTok{"Ignorado"}\NormalTok{, edad\_hombre\_grupo }\SpecialCharTok{!=} \StringTok{"Ignorado"}\NormalTok{)}

\CommentTok{\# Mujer}
\NormalTok{tabla\_matr\_mujer }\OtherTok{\textless{}{-}}\NormalTok{ matr\_edad\_cat }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(edad\_mujer\_grupo) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total =} \FunctionTok{sum}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{prop =}\NormalTok{ total }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(total)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(total))}

\NormalTok{tabla\_div\_mujer }\OtherTok{\textless{}{-}}\NormalTok{ div\_edad\_cat }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(edad\_mujer\_grupo) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total =} \FunctionTok{sum}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{prop =}\NormalTok{ total }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(total)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(total))}

\CommentTok{\# Hombre}
\NormalTok{tabla\_matr\_hombre }\OtherTok{\textless{}{-}}\NormalTok{ matr\_edad\_cat }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(edad\_hombre\_grupo) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total =} \FunctionTok{sum}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{prop =}\NormalTok{ total }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(total)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(total))}

\NormalTok{tabla\_div\_hombre }\OtherTok{\textless{}{-}}\NormalTok{ div\_edad\_cat }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(edad\_hombre\_grupo) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total =} \FunctionTok{sum}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{prop =}\NormalTok{ total }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(total)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(total))}

\NormalTok{tabla\_matr\_mujer}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 14 x 3
##    edad_mujer_grupo  total    prop
##    <chr>             <dbl>   <dbl>
##  1 20 - 24          352716 0.336  
##  2 25 - 29          207469 0.197  
##  3 15 - 19          177653 0.169  
##  4 30 - 34          105866 0.101  
##  5 35 - 39           55252 0.0526 
##  6 40 - 44           32255 0.0307 
##  7 Menos de 20       32206 0.0306 
##  8 45 - 49           22377 0.0213 
##  9 50 - 54           15903 0.0151 
## 10 18 - 19           12810 0.0122 
## 11 55 - 59           11564 0.0110 
## 12 65 y más          10597 0.0101 
## 13 60 - 64            8035 0.00764
## 14 Menos de 15        6594 0.00627
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tabla\_div\_mujer}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 13 x 3
##    edad_mujer_grupo total     prop
##    <chr>            <dbl>    <dbl>
##  1 25 - 29           9781 0.259   
##  2 30 - 34           8235 0.218   
##  3 20 - 24           6367 0.168   
##  4 35 - 39           5203 0.138   
##  5 40 - 44           3175 0.0840  
##  6 45 - 49           1748 0.0463  
##  7 15 - 19           1312 0.0347  
##  8 50 - 54            940 0.0249  
##  9 55 - 59            526 0.0139  
## 10 60 y más           399 0.0106  
## 11 Menos de 15         47 0.00124 
## 12 18 - 19             39 0.00103 
## 13 Menos de 20         16 0.000423
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tabla\_matr\_hombre}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 14 x 3
##    edad_hombre_grupo  total      prop
##    <chr>              <dbl>     <dbl>
##  1 20-24             342479 0.326    
##  2 25-29             260128 0.247    
##  3 30-34             141959 0.135    
##  4 15-19              74117 0.0705   
##  5 35-39              73538 0.0699   
##  6 40-44              41818 0.0398   
##  7 45-49              27244 0.0259   
##  8 65 y más           23194 0.0221   
##  9 50-54              20770 0.0198   
## 10 55-59              16945 0.0161   
## 11 60-64              14591 0.0139   
## 12 Menos de 20        10177 0.00968  
## 13 18-19               4285 0.00408  
## 14 Menos de 15           52 0.0000495
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tabla\_div\_hombre}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 13 x 3
##    edad_hombre_grupo total      prop
##    <chr>             <dbl>     <dbl>
##  1 30-34              9245 0.245    
##  2 25-29              8416 0.223    
##  3 35-39              6439 0.170    
##  4 40-44              4084 0.108    
##  5 20-24              3386 0.0896   
##  6 45-49              2461 0.0651   
##  7 50-54              1439 0.0381   
##  8 60 y más           1050 0.0278   
##  9 55-59               901 0.0238   
## 10 15-19               362 0.00958  
## 11 Menos de 20           4 0.000106 
## 12 18-19                 1 0.0000265
## 13 Menos de 15           0 0
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(tabla\_matr\_mujer, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{reorder}\NormalTok{(edad\_mujer\_grupo, prop), }\AttributeTok{y =}\NormalTok{ prop)) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{coord\_flip}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{labels =}\NormalTok{ scales}\SpecialCharTok{::}\NormalTok{percent) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Proporción de matrimonios por rango de edad (mujer)"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Rango de edad"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Proporción"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-12-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(tabla\_div\_mujer, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{reorder}\NormalTok{(edad\_mujer\_grupo, prop), }\AttributeTok{y =}\NormalTok{ prop)) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{coord\_flip}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{labels =}\NormalTok{ scales}\SpecialCharTok{::}\NormalTok{percent) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Proporción de divorcios por rango de edad (mujer)"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Rango de edad"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Proporción"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-12-2.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(tabla\_matr\_hombre, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{reorder}\NormalTok{(edad\_hombre\_grupo, prop), }\AttributeTok{y =}\NormalTok{ prop)) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{coord\_flip}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{labels =}\NormalTok{ scales}\SpecialCharTok{::}\NormalTok{percent) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Proporción de matrimonios por rango de edad (hombre)"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Rango de edad"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Proporción"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-12-3.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(tabla\_div\_hombre, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{reorder}\NormalTok{(edad\_hombre\_grupo, prop), }\AttributeTok{y =}\NormalTok{ prop)) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+} \FunctionTok{coord\_flip}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{labels =}\NormalTok{ scales}\SpecialCharTok{::}\NormalTok{percent) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Proporción de divorcios por rango de edad (hombre)"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Rango de edad"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Proporción"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-12-4.pdf}}

\textbf{Rangos de edad en mujeres}

En matrimonios, el rango más frecuente para mujeres es 20--24 años, con
352,716 registros (33.55\%). Le siguen 25--29 años con 207,469
(19.73\%), y 15--19 años con 177,653 (16.90\%). Esto muestra una
concentración fuerte en edades jóvenes-adultas, particularmente en el
rango de 20--24 años.

En divorcios, la distribución se desplaza hacia edades mayores: el rango
más frecuente es 25--29 años con 9,781 (25.88\%), seguido de 30--34 años
con 8,235 (21.79\%), y luego 20--24 años con 6,367 (16.85\%). En
comparación con matrimonios, los divorcios aparecen con mayor frecuencia
en rangos que corresponden a edades ligeramente más avanzadas.

\textbf{Rangos de edad en hombres}

En matrimonios, el rango más frecuente para hombres también es 20--24
años, con 342,479 (32.58\%), seguido por 25--29 años con 260,128
(24.74\%), y en tercer lugar 30--34 años con 141,959 (13.50\%). La
concentración se mantiene en el periodo de adultez temprana, aunque se
nota un mayor peso relativo en rangos ligeramente superiores en
comparación con mujeres (por ejemplo, 30--34 aparece en el top 3).

En divorcios, el pico principal está en edades más altas: 30--34 años
con 9,245 (24.47\%), seguido por 25--29 años con 8,416 (22.27\%), y
luego 35--39 años con 6,439 (17.04\%). Esto refuerza la idea de que los
divorcios tienden a concentrarse en rangos posteriores a los que
concentran matrimonios.

Finalmente, los gráficos permiten detectar un aspecto relevante: en la
distribución de matrimonios por edad de mujeres aparecen registros en el
grupo ``Menos de 15'', mientras que en los hombres no aparecen registros
menores de 15. Esto es alarmante, porque se evidencia la posible
presencia de matrimonios con mujeres menores de edad con hombres mayores
de edad.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection{\texorpdfstring{\textbf{Relaciones entre
Variables}}{Relaciones entre Variables}}\label{relaciones-entre-variables}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{matrimonios\_depto\_clean }\OtherTok{\textless{}{-}} \FunctionTok{filter}\NormalTok{(matrimonios\_depto, nivel\_geo }\SpecialCharTok{==} \StringTok{"departamento"} \SpecialCharTok{\&} \SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(mes))}
\NormalTok{divorcios\_depto\_clean }\OtherTok{\textless{}{-}} \FunctionTok{filter}\NormalTok{(divorcios\_depto, nivel\_geo }\SpecialCharTok{==} \StringTok{"departamento"} \SpecialCharTok{\&} \SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(mes))}

\NormalTok{to\_mid\_age }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x)\{}
\NormalTok{  x }\OtherTok{\textless{}{-}} \FunctionTok{str\_trim}\NormalTok{(x)}
  \ControlFlowTok{if}\NormalTok{ (x }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"Ignorado"}\NormalTok{, }\StringTok{"Menos de 15"}\NormalTok{)) }\FunctionTok{return}\NormalTok{(}\ConstantTok{NA\_real\_}\NormalTok{)}
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{str\_detect}\NormalTok{(x, }\StringTok{"60"}\NormalTok{)) }\FunctionTok{return}\NormalTok{(}\DecValTok{60}\NormalTok{) }\CommentTok{\# "60 y más"}
\NormalTok{  nums }\OtherTok{\textless{}{-}} \FunctionTok{str\_extract\_all}\NormalTok{(x, }\StringTok{"}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{d+"}\NormalTok{)[[}\DecValTok{1}\NormalTok{]]}
  \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{length}\NormalTok{(nums) }\SpecialCharTok{==} \DecValTok{2}\NormalTok{) }\FunctionTok{return}\NormalTok{(}\FunctionTok{mean}\NormalTok{(}\FunctionTok{as.numeric}\NormalTok{(nums)))}
  \ConstantTok{NA\_real\_}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Relacion entre edades de mujeres y hombres en la decision de casarse.
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Al tratarse de datos con valores comunes, no se puede utilizar un
  gráfico de dispersión ``común y corriente'', así que se decidió usar
  uno de burbujas (tamaño proporcional al conteo). En este gráfico
  podemos observar que las burbujas más grandes no se encuentran sobre
  la diagonal de relación, sino más bien en la parte inferior del
  diagrama, lo cual sugiere que no hay una relación fuerte entre la edad
  del hombre y la de la mujer al momento de casarse.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{matrimonios\_edad\_plot }\OtherTok{\textless{}{-}}\NormalTok{ matrimonios\_edad }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{edad\_h =} \FunctionTok{sapply}\NormalTok{(edad\_hombre\_grupo, to\_mid\_age),}
    \AttributeTok{edad\_m =} \FunctionTok{sapply}\NormalTok{(edad\_mujer\_grupo, to\_mid\_age)}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(edad\_h), }\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(edad\_m))}

\FunctionTok{ggplot}\NormalTok{(matrimonios\_edad\_plot, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ edad\_h, }\AttributeTok{y =}\NormalTok{ edad\_m)) }\SpecialCharTok{+}
  \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{slope =} \DecValTok{1}\NormalTok{, }\AttributeTok{intercept =} \DecValTok{0}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{size =}\NormalTok{ valor), }\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Matrimonios: edad hombre vs edad mujer"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Edad (hombre, punto medio del grupo)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Edad (mujer, punto medio del grupo)"}\NormalTok{,}
    \AttributeTok{size =} \StringTok{"Cantidad (valor)"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/Relation of Age and Marriage-1.pdf}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  Relacion entre edades de mujeres y hombres en la decision de
  divorciarse
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Al tratarse de datos con valores comunes, no se puede utilizar un
  gráfico de dispersión ``común y corriente'', así que se decidió usar
  uno de burbujas (tamaño proporcional al conteo). En este gráfico
  podemos observar que las burbujas más grandes sí se encuentran sobre
  la diagonal de relación, aunque con cierta dispersión, lo cual sugiere
  que existe una relación moderada entre la edad del hombre y la de la
  mujer al momento de divorciarse.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{divorcios\_edad\_plot }\OtherTok{\textless{}{-}}\NormalTok{ divorcios\_edad }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{edad\_h =} \FunctionTok{sapply}\NormalTok{(edad\_hombre\_grupo, to\_mid\_age),}
    \AttributeTok{edad\_m =} \FunctionTok{sapply}\NormalTok{(edad\_mujer\_grupo, to\_mid\_age)}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(edad\_h), }\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(edad\_m))}

\FunctionTok{ggplot}\NormalTok{(divorcios\_edad\_plot, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ edad\_h, }\AttributeTok{y =}\NormalTok{ edad\_m)) }\SpecialCharTok{+}
  \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{slope =} \DecValTok{1}\NormalTok{, }\AttributeTok{intercept =} \DecValTok{0}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{size =}\NormalTok{ valor), }\AttributeTok{alpha =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Divorcios: edad hombre vs edad mujer"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Edad (hombre, punto medio del grupo)"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Edad (mujer, punto medio del grupo)"}\NormalTok{,}
    \AttributeTok{size =} \StringTok{"Cantidad (valor)"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/Relation of Age and Divorce-1.pdf}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  La relación entre la cantidad de matrimonios y la cantidad de
  divorcios es de 0.603 (coeficiente de correlación de Pearson), lo cual
  indica una relación moderada. En general, a mayor tasa de matrimonios,
  mayor tasa de divorcios, aunque con variabilidad considerable.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{number\_of\_divorcios\_por\_anio }\OtherTok{\textless{}{-}}\NormalTok{ divorcios\_depto\_clean }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(anio) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total\_divorcios =} \FunctionTok{sum}\NormalTok{(valor))}

\NormalTok{number\_of\_matrimonios\_por\_anio }\OtherTok{\textless{}{-}}\NormalTok{ matrimonios\_depto\_clean }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(anio) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total\_divorcios =} \FunctionTok{sum}\NormalTok{(valor))}

\NormalTok{matrimonios\_vs\_divorcios }\OtherTok{\textless{}{-}}\NormalTok{ number\_of\_matrimonios\_por\_anio }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{inner\_join}\NormalTok{(number\_of\_divorcios\_por\_anio, }\AttributeTok{by =} \FunctionTok{c}\NormalTok{(}\StringTok{"anio"}\NormalTok{))}
\FunctionTok{colnames}\NormalTok{(matrimonios\_vs\_divorcios) }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"anio"}\NormalTok{, }\StringTok{"total\_matrimonios"}\NormalTok{, }\StringTok{"total\_divorcios"}\NormalTok{)}

\FunctionTok{ggplot}\NormalTok{(matrimonios\_vs\_divorcios, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ total\_divorcios, }\AttributeTok{y =}\NormalTok{ total\_matrimonios)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Matrimonios: edad hombre vs edad mujer"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Divorcios"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Matrimonios"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/Relation for Marrige and Divorce-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{correlation\_coefficient }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(matrimonios\_vs\_divorcios}\SpecialCharTok{$}\NormalTok{total\_matrimonios, matrimonios\_vs\_divorcios}\SpecialCharTok{$}\NormalTok{total\_divorcios)}
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Coefficiente de Correlacion entre Matrimonios and Divorcios:"}\NormalTok{, correlation\_coefficient))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Coefficiente de Correlacion entre Matrimonios and Divorcios: 0.603599487196953"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Porcentaje de :"}\NormalTok{, correlation\_coefficient))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Porcentaje de : 0.603599487196953"
\end{verbatim}

\subsection{\texorpdfstring{\textbf{Clustering}}{Clustering}}\label{clustering}

\subsubsection{\texorpdfstring{\textbf{Número de
Clusters}}{Número de Clusters}}\label{nuxfamero-de-clusters}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{matrimonios\_anual }\OtherTok{\textless{}{-}}\NormalTok{ matrimonios\_depto }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}
\NormalTok{    nivel\_geo }\SpecialCharTok{==} \StringTok{"departamento"}\NormalTok{,}
    \FunctionTok{is.na}\NormalTok{(mes),}
    \SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(departamento)}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{departamento =} \FunctionTok{norm\_depto}\NormalTok{(departamento)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(anio, departamento) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{matrimonios =} \FunctionTok{sum}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{)}

\NormalTok{divorcios\_anual }\OtherTok{\textless{}{-}}\NormalTok{ divorcios\_depto }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}
\NormalTok{    nivel\_geo }\SpecialCharTok{==} \StringTok{"departamento"}\NormalTok{,}
    \FunctionTok{is.na}\NormalTok{(mes),}
    \SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(departamento)}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{departamento =} \FunctionTok{norm\_depto}\NormalTok{(departamento)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(anio, departamento) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{divorcios =} \FunctionTok{sum}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{)}

\NormalTok{matrimonios\_divorcios\_depto\_anual }\OtherTok{\textless{}{-}} \FunctionTok{full\_join}\NormalTok{(}
\NormalTok{  matrimonios\_anual,}
\NormalTok{  divorcios\_anual,}
  \AttributeTok{by =} \FunctionTok{c}\NormalTok{(}\StringTok{"anio"}\NormalTok{, }\StringTok{"departamento"}\NormalTok{)}
\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{ratio\_div\_matr =}\NormalTok{ divorcios }\SpecialCharTok{/}\NormalTok{ matrimonios}
\NormalTok{  )}


\NormalTok{depto\_stats }\OtherTok{\textless{}{-}}\NormalTok{ matrimonios\_divorcios\_depto\_anual }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(departamento) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{avg\_matrimonios =} \FunctionTok{mean}\NormalTok{(matrimonios, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{avg\_divorcios   =} \FunctionTok{mean}\NormalTok{(divorcios, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{ratio\_div\_matr  =}\NormalTok{ avg\_divorcios }\SpecialCharTok{/}\NormalTok{ avg\_matrimonios,}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  )}

\NormalTok{dept\_labels }\OtherTok{\textless{}{-}}\NormalTok{ depto\_stats}\SpecialCharTok{$}\NormalTok{departamento}
\NormalTok{depto\_stats\_num }\OtherTok{\textless{}{-}}\NormalTok{ depto\_stats }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{departamento)}
\NormalTok{depto\_stats\_num\_scaled }\OtherTok{\textless{}{-}} \FunctionTok{scale}\NormalTok{(depto\_stats\_num)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{fviz\_nbclust}\NormalTok{(depto\_stats\_num\_scaled, kmeans, }\AttributeTok{method =} \StringTok{"wss"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-14-1.pdf}}

Utilizando el método del codo, se logra identificar que el punto en
donde se identifica que el gráfico deja de ser pronunciado y empieza a
estabilizarse es en 3.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{fviz\_nbclust}\NormalTok{(depto\_stats\_num\_scaled, kmeans, }\AttributeTok{method =} \StringTok{"silhouette"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-15-1.pdf}}

Para garantizar una selección adecuada de clusters, se decidió hacer la
prueba por método de la silueta. Al realizarlo, vemos que el punto
óptimo señalado es 3. Tomando en consideración ambos métodos, para
nuestro clustering utilizaremos k=3.

\subsubsection{\texorpdfstring{\textbf{Agrupamiento y
Tendencia}}{Agrupamiento y Tendencia}}\label{agrupamiento-y-tendencia}

Para este caso se estará trabajando con k-means para agrupar los
elementos.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{56}\NormalTok{)}
\NormalTok{kmeans\_model }\OtherTok{\textless{}{-}} \FunctionTok{kmeans}\NormalTok{(depto\_stats\_num\_scaled, }\AttributeTok{centers =} \DecValTok{3}\NormalTok{, }\AttributeTok{nstart =} \DecValTok{25}\NormalTok{)}
\NormalTok{sil }\OtherTok{\textless{}{-}} \FunctionTok{silhouette}\NormalTok{(kmeans\_model}\SpecialCharTok{$}\NormalTok{cluster, }\FunctionTok{dist}\NormalTok{(depto\_stats\_num\_scaled))}
\FunctionTok{mean}\NormalTok{(sil[, }\DecValTok{3}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.4915747
\end{verbatim}

Para evaluar la tendencia al agrupamiento se encontró el coeficiente
promedio de silueta para k=3 y este fue de 0.4915, lo cual indica una
separación fuerte. Esto indica que nuestros datos pueden ser separados
en clusters.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{fviz\_cluster}\NormalTok{(kmeans\_model, }\AttributeTok{data =}\NormalTok{ depto\_stats\_num\_scaled,}
             \AttributeTok{geom =} \StringTok{"point"}\NormalTok{,}
             \AttributeTok{ellipse.type =} \StringTok{"convex"}\NormalTok{,}
             \AttributeTok{ggtheme =} \FunctionTok{theme\_minimal}\NormalTok{())}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-17-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{depto\_clusters }\OtherTok{\textless{}{-}}\NormalTok{ depto\_stats }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{cluster =}\NormalTok{ kmeans\_model}\SpecialCharTok{$}\NormalTok{cluster) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(cluster, }\FunctionTok{desc}\NormalTok{(ratio\_div\_matr))}

\NormalTok{depto\_clusters}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 22 x 5
##    departamento   avg_matrimonios avg_divorcios ratio_div_matr cluster
##    <chr>                    <dbl>         <dbl>          <dbl>   <int>
##  1 guatemala               15282          2272.         0.149        1
##  2 el progreso               860           109.         0.127        2
##  3 zacapa                   1213.          151.         0.124        2
##  4 izabal                   1741           186.         0.107        2
##  5 jalapa                   1463.          149.         0.102        2
##  6 quetzaltenango           4607.          459.         0.0996       2
##  7 jutiapa                  2434.          225.         0.0923       2
##  8 retalhuleu               1898.          174          0.0917       2
##  9 santa rosa               1816.          164.         0.0902       2
## 10 chiquimula               1672.          149.         0.0891       2
## # i 12 more rows
\end{verbatim}

En este caso se obtuvieron tres grupos. El primer grupo contiene
únicamente al departamento de Guatemala, el cual presenta valores
promedio de matrimonios y divorcios considerablemente más altos que el
resto. En particular, registra aproximadamente 15,282 matrimonios
promedio y 2,272 divorcios promedio. En contraste, los demás
departamentos presentan promedios notablemente menores (aprox. 800 a
6,000 matrimonios y 65 a 458 divorcios). Esto sugiere que Guatemala se
comporta de manera diferenciada.

\subsubsection{\texorpdfstring{\textbf{Calidad de
Agrupamiento}}{Calidad de Agrupamiento}}\label{calidad-de-agrupamiento}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(sil)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Silhouette of 22 units in 3 clusters from silhouette.default(x = kmeans_model$cluster, dist = dist(depto_stats_num_scaled)) :
##  Cluster sizes and average silhouette widths:
##         1        13         8 
## 0.0000000 0.4761679 0.5780577 
## Individual silhouette widths:
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.0000  0.3491  0.5986  0.4916  0.6574  0.7148
\end{verbatim}

El coeficiente promedio de silueta obtenido fue 0.4916 lo que indica un
agrupamiento aceptable. Al analizar por cluster, se observa que un grupo
presenta un valor promedio de 0.4762 (cluster bueno), otro grupo de
0.5781 (cl.uster muy bueno), y otro que está en cero. Este tercer
cluster presenta un valor promedio de 0.00, pero esto se debe a que es
un cluster unitario, y es que este elemnto pertenece a un caso atípico
que es el departamento de Guatemala, el cual tiene magnitudes bastante
superiores a las presentadas a comparación de todos los demás
departamentos, por lo que fue separado a un grupo propio.

\subsubsection{\texorpdfstring{\textbf{Interpretación de
grupos}}{Interpretación de grupos}}\label{interpretaciuxf3n-de-grupos}

\textbf{Cluster 1}

Aquí solo tenemos a Guatemala es el caso atípico, tenemos promedios
muchos más altos en matrimonios y divorcios, así como un ratio mayor al
de los demás con 0.149.

\textbf{Cluster 2}

Tiene una proporción media alta de divorcios con respecto a matrimonios
(entre 0.065 y 0.127).

Departamentos pertenecientes:

\begin{itemize}
\item
  El Progreso
\item
  Zacapa
\item
  Izabal
\item
  Jalapa
\item
  Quetzaltenango
\item
  Jutiapa
\item
  Retalhuleu
\item
  Santa Rosa
\item
  Chiquimula
\item
  Escuintla
\item
  Baja Verapaz
\item
  Petén
\item
  Sacatepéquez
\end{itemize}

\textbf{Cluster 3}

Departamentos con una baja proporción de divorcios respecto a
matrimonios (valores menores a 0.059). Cabe destacar que en este grupo
aparecen varios departamentos con algunos de los promedios más altos de
matrimonios como Huehuetenango y Alta Verapaz.

\begin{itemize}
\item
  Suchitepéquez
\item
  San Marcos
\item
  Totonicapán
\item
  Huehuetenango
\item
  Chimaltenango
\item
  Sololá
\item
  Quiché
\item
  Alta Verapaz
\end{itemize}

\subsubsection{\texorpdfstring{\textbf{Preguntas de
Investigación}}{Preguntas de Investigación}}\label{preguntas-de-investigaciuxf3n}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  ¿Se ha observado un cambio en la edad promedio en la que las personas
  contraen matrimonio en Guatemala, indicando que se casan a mayor edad?
\end{enumerate}

Se puede observar que se compararon las combinaciones de edad más
frecuentes en matrimonios entre los periodos 2009-2012 y 2019-2022. Los
resultados muestran que en ambos periodos predominan las parejas en
donde el hombre y la mujer tienen entre 20 y 24 años, seguidas por los
rangos entre 25 y 29 años. Aunque en el periodo de 2019-2022 se pueden
observar algunos rangos ligeramente mayores estos no superan a los
grupos principales. Por lo tanto no se identifica un cambio
significativo hacia edades más altas en los matrimonios. Por
consiguiente no se observa un cambio en la edad promedio en que las
personas contraen matrimonio en Guatemala.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Periodos matrimonios}
\NormalTok{matr\_periodos }\OtherTok{\textless{}{-}}\NormalTok{ matrimonios\_edad\_limpio }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{periodo =} \FunctionTok{case\_when}\NormalTok{(}
\NormalTok{      anio }\SpecialCharTok{\textgreater{}=} \DecValTok{2009} \SpecialCharTok{\&}\NormalTok{ anio }\SpecialCharTok{\textless{}=} \DecValTok{2012} \SpecialCharTok{\textasciitilde{}} \StringTok{"2009–2012"}\NormalTok{,}
\NormalTok{      anio }\SpecialCharTok{\textgreater{}=} \DecValTok{2019} \SpecialCharTok{\&}\NormalTok{ anio }\SpecialCharTok{\textless{}=} \DecValTok{2022} \SpecialCharTok{\textasciitilde{}} \StringTok{"2019–2022"}\NormalTok{,}
      \ConstantTok{TRUE} \SpecialCharTok{\textasciitilde{}} \ConstantTok{NA\_character\_}
\NormalTok{    )}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(periodo))}

\CommentTok{\# tabla de matrimonios }
\NormalTok{tabla\_top10 }\OtherTok{\textless{}{-}}\NormalTok{ matr\_periodos }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(periodo, edad\_mujer\_grupo, edad\_hombre\_grupo) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total\_matrimonios =} \FunctionTok{sum}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{arrange}\NormalTok{(periodo, }\FunctionTok{desc}\NormalTok{(total\_matrimonios)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(periodo) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{slice\_head}\NormalTok{(}\AttributeTok{n =} \DecValTok{10}\NormalTok{)}

\NormalTok{tabla\_top10}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 20 x 4
## # Groups:   periodo [2]
##    periodo   edad_mujer_grupo edad_hombre_grupo total_matrimonios
##    <chr>     <chr>            <chr>                         <dbl>
##  1 2009–2012 20 - 24          20-24                         45282
##  2 2009–2012 15 - 19          20-24                         41155
##  3 2009–2012 20 - 24          25-29                         28886
##  4 2009–2012 15 - 19          15-19                         24695
##  5 2009–2012 25 - 29          25-29                         20847
##  6 2009–2012 25 - 29          30-34                         13096
##  7 2009–2012 15 - 19          25-29                         11826
##  8 2009–2012 25 - 29          20-24                          9809
##  9 2009–2012 30 - 34          30-34                          8947
## 10 2009–2012 20 - 24          30-34                          8003
## 11 2019–2022 20 - 24          20-24                         51572
## 12 2019–2022 20 - 24          25-29                         34679
## 13 2019–2022 25 - 29          25-29                         29346
## 14 2019–2022 Menos de 20      20-24                         18887
## 15 2019–2022 25 - 29          30-34                         17253
## 16 2019–2022 30 - 34          30-34                         12785
## 17 2019–2022 25 - 29          20-24                         11231
## 18 2019–2022 20 - 24          30-34                          8967
## 19 2019–2022 30 - 34          35-39                          7950
## 20 2019–2022 18 - 19          20-24                          7497
\end{verbatim}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  ¿La tasa promedio de divorcios por cada 100 matrimonios es mayor en el
  departamento de Guatemala que en el interior del país?
\end{enumerate}

\begin{itemize}
\tightlist
\item
  La taza de divorcios por cada 100 matrimonios es mucho mayor en la
  Ciudad de Guatemala a comparacion del interior del país, esto siendo
  una diferencia casi del doble con 14.87 en guatemala en promedio y
  6.03 en el interior de promedio, esto posiblemente nos puede indicar
  que en la capital el divorcio no es tan mal visto a comparacion del
  interior.
\item
  Adicionalmente, para descartar posibles desequilibrios por los
  promedios, si observamos los graficos de barra podemos confirmar estos
  numeros viendo que incluso los divorcios de Quetzaltenango no llegan
  ni siquiera cerca de los que ocurren el la Capital.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{divorcios\_por\_depto }\OtherTok{\textless{}{-}}\NormalTok{ divorcios\_depto\_clean }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{departamento =} \FunctionTok{stri\_trans\_general}\NormalTok{(departamento, }\StringTok{"Latin{-}ASCII"}\NormalTok{)) }\SpecialCharTok{|\textgreater{}}  \CommentTok{\# quita tildes}
  \FunctionTok{group\_by}\NormalTok{(departamento) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{promedio\_divorcios =} \FunctionTok{mean}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(promedio\_divorcios))}

\NormalTok{matrimonios\_por\_depto }\OtherTok{\textless{}{-}}\NormalTok{ matrimonios\_depto\_clean }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{departamento =} \FunctionTok{stri\_trans\_general}\NormalTok{(departamento, }\StringTok{"Latin{-}ASCII"}\NormalTok{)) }\SpecialCharTok{|\textgreater{}}  \CommentTok{\# quita tildes}
  \FunctionTok{group\_by}\NormalTok{(departamento) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{promedio\_matrimonios =} \FunctionTok{mean}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(promedio\_matrimonios))}

\FunctionTok{ggplot}\NormalTok{(divorcios\_por\_depto, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{reorder}\NormalTok{(departamento, promedio\_divorcios), }\AttributeTok{y =}\NormalTok{ promedio\_divorcios)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"steelblue"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{coord\_flip}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Promedio de Divorcios por Departamento"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Departamento"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Promedio de Divorcios"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/capital vs interior-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(matrimonios\_por\_depto, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{reorder}\NormalTok{(departamento, promedio\_matrimonios), }\AttributeTok{y =}\NormalTok{ promedio\_matrimonios)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"steelblue"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{coord\_flip}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Promedio de Matrimonios por Departamento"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Departamento"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Promedio de Matrimonios"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/capital vs interior-2.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# promedio de guatemala vs el resto del pais}
\NormalTok{divorcios\_guatemala }\OtherTok{\textless{}{-}}\NormalTok{ divorcios\_depto\_clean }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(departamento }\SpecialCharTok{==} \StringTok{"guatemala"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{promedio\_divorcios\_guatemala =} \FunctionTok{mean}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}

\NormalTok{divorcios\_resto }\OtherTok{\textless{}{-}}\NormalTok{ divorcios\_depto\_clean }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(departamento }\SpecialCharTok{!=} \StringTok{"guatemala"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{promedio\_divorcios\_resto =} \FunctionTok{mean}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}

\NormalTok{matrimonios\_guatemala }\OtherTok{\textless{}{-}}\NormalTok{ matrimonios\_depto\_clean }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(departamento }\SpecialCharTok{==} \StringTok{"guatemala"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{promedio\_matrimonios\_guatemala =} \FunctionTok{mean}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{)) }

\NormalTok{matrimonios\_resto }\OtherTok{\textless{}{-}}\NormalTok{ matrimonios\_depto\_clean }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(departamento }\SpecialCharTok{!=} \StringTok{"guatemala"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{promedio\_matrimonios\_resto =} \FunctionTok{mean}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{))}

\CommentTok{\# tasa de divorcios por cada 100 matrimonios}
\NormalTok{tasa\_divorcios\_guatemala }\OtherTok{\textless{}{-}}\NormalTok{ (divorcios\_guatemala}\SpecialCharTok{$}\NormalTok{promedio\_divorcios\_guatemala }\SpecialCharTok{/}\NormalTok{ matrimonios\_guatemala}\SpecialCharTok{$}\NormalTok{promedio\_matrimonios\_guatemala) }\SpecialCharTok{*} \DecValTok{100}
\NormalTok{tasa\_divorcios\_resto }\OtherTok{\textless{}{-}}\NormalTok{ (divorcios\_resto}\SpecialCharTok{$}\NormalTok{promedio\_divorcios\_resto }\SpecialCharTok{/}\NormalTok{ matrimonios\_resto}\SpecialCharTok{$}\NormalTok{promedio\_matrimonios\_resto) }\SpecialCharTok{*} \DecValTok{100}

\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Tasa de Divorcios por cada 100 Matrimonios en Guatemala:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(tasa\_divorcios\_guatemala, }\DecValTok{2}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Tasa de Divorcios por cada 100 Matrimonios en Guatemala: 14.87"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{paste}\NormalTok{(}\StringTok{"Tasa de Divorcios por cada 100 Matrimonios en el resto del país:"}\NormalTok{, }\FunctionTok{round}\NormalTok{(tasa\_divorcios\_resto, }\DecValTok{2}\NormalTok{)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Tasa de Divorcios por cada 100 Matrimonios en el resto del país: 6.03"
\end{verbatim}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  ¿Se observa un incremento en el número promedio anual de divorcios en
  años recientes (2019--2022) frente a hace una década (2009--2012), lo
  cual podría sugerir cambios sociales?
\end{enumerate}

\begin{itemize}
\tightlist
\item
  Si observamos las tablas y el gráfico de barras podemos observar que
  los divorcios de 2019-2022 han incrementado el doble que hace 10 años
  (2009-2012) lo cual posiblemente nos podría indicar que sí ha habido
  un cambio social sobre la aceptación del divorcio.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# divorcios de 2019 a 2022}
\NormalTok{divorcios\_2019\_2022 }\OtherTok{\textless{}{-}}\NormalTok{ divorcios\_depto\_clean }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(anio }\SpecialCharTok{\textgreater{}=} \DecValTok{2019} \SpecialCharTok{\&}\NormalTok{ anio }\SpecialCharTok{\textless{}=} \DecValTok{2022}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(anio) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total\_divorcios =} \FunctionTok{sum}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{)}

\CommentTok{\# divorcios de 2009 a 2012}
\NormalTok{divorcios\_2009\_2012 }\OtherTok{\textless{}{-}}\NormalTok{ divorcios\_depto\_clean }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{(anio }\SpecialCharTok{\textgreater{}=} \DecValTok{2009} \SpecialCharTok{\&}\NormalTok{ anio }\SpecialCharTok{\textless{}=} \DecValTok{2012}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(anio) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total\_divorcios =} \FunctionTok{sum}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{)}

\NormalTok{divorcios\_2019\_2022}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4 x 2
##    anio total_divorcios
##   <dbl>           <dbl>
## 1  2019            8203
## 2  2020            4074
## 3  2021            9621
## 4  2022            9950
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{divorcios\_2009\_2012}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 4 x 2
##    anio total_divorcios
##   <dbl>           <dbl>
## 1  2009            3004
## 2  2010            3645
## 3  2011            4344
## 4  2012            5157
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# promedios por anios}
\NormalTok{div\_periodo }\OtherTok{\textless{}{-}}\NormalTok{ divorcios\_depto\_clean }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{filter}\NormalTok{((anio }\SpecialCharTok{\textgreater{}=} \DecValTok{2009} \SpecialCharTok{\&}\NormalTok{ anio }\SpecialCharTok{\textless{}=} \DecValTok{2012}\NormalTok{) }\SpecialCharTok{|}\NormalTok{ (anio }\SpecialCharTok{\textgreater{}=} \DecValTok{2019} \SpecialCharTok{\&}\NormalTok{ anio }\SpecialCharTok{\textless{}=} \DecValTok{2022}\NormalTok{)) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(anio) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total\_anual =} \FunctionTok{sum}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{periodo =} \FunctionTok{ifelse}\NormalTok{(anio }\SpecialCharTok{\textless{}=} \DecValTok{2012}\NormalTok{, }\StringTok{"2009–2012"}\NormalTok{, }\StringTok{"2019–2022"}\NormalTok{)) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{group\_by}\NormalTok{(periodo) }\SpecialCharTok{|\textgreater{}}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{promedio\_anual =} \FunctionTok{mean}\NormalTok{(total\_anual), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{)}

\FunctionTok{ggplot}\NormalTok{(div\_periodo, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ periodo, }\AttributeTok{y =}\NormalTok{ promedio\_anual)) }\SpecialCharTok{+}
  \FunctionTok{geom\_col}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Promedio anual de divorcios por periodo"}\NormalTok{,}
       \AttributeTok{x =} \StringTok{"Periodo"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Promedio anual (total por año)"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/divorcios ahora vs hace 10 anios-1.pdf}}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

4.¿Los departamentos con menor cantidad de matrimonios presentan una
proporción considerablemente menor de divorcios?

Contrario a la hipótesis inicial, al agrupar los departamentos según su
volumen total de matrimonios (2009--2022), se observa que el grupo de
menor volumen presenta la tasa promedio de divorcios más alta (12.63
divorcios por cada 100 matrimonios), mientras que el grupo de mayor
volumen presenta la más baja (6.12).

Esto contradice la creencia de que donde hay menos matrimonios también
hay proporcionalmente menos divorcios. Sin embargo, este resultado debe
interpretarse con cautela, ya que el grupo ``Bajo'' contiene únicamente
2 departamentos y la categorización se basa en volumen de matrimonios,
no en un indicador directo de urbanización.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Calcular totales y tasas por departamento}
\NormalTok{analisis\_rural\_urbano }\OtherTok{\textless{}{-}}\NormalTok{ matrimonios\_depto }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(nivel\_geo }\SpecialCharTok{==} \StringTok{"departamento"}\NormalTok{, }\FunctionTok{is.na}\NormalTok{(mes)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(departamento) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total\_matrimonios =} \FunctionTok{sum}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{left\_join}\NormalTok{(}
\NormalTok{    divorcios\_depto }\SpecialCharTok{\%\textgreater{}\%}
      \FunctionTok{filter}\NormalTok{(nivel\_geo }\SpecialCharTok{==} \StringTok{"departamento"}\NormalTok{, }\FunctionTok{is.na}\NormalTok{(mes)) }\SpecialCharTok{\%\textgreater{}\%}
      \FunctionTok{group\_by}\NormalTok{(departamento) }\SpecialCharTok{\%\textgreater{}\%}
      \FunctionTok{summarise}\NormalTok{(}\AttributeTok{total\_divorcios =} \FunctionTok{sum}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{),}
    \AttributeTok{by =} \StringTok{"departamento"}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{total\_divorcios =}\NormalTok{ tidyr}\SpecialCharTok{::}\FunctionTok{replace\_na}\NormalTok{(total\_divorcios, }\DecValTok{0}\NormalTok{),}
    \AttributeTok{tasa\_divorcio\_por\_100 =}\NormalTok{ (total\_divorcios }\SpecialCharTok{/}\NormalTok{ total\_matrimonios) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{,}
    \AttributeTok{categoria =} \FunctionTok{case\_when}\NormalTok{(}
\NormalTok{      total\_matrimonios }\SpecialCharTok{\textgreater{}} \DecValTok{40000} \SpecialCharTok{\textasciitilde{}} \StringTok{"Alto"}\NormalTok{,}
\NormalTok{      total\_matrimonios }\SpecialCharTok{\textgreater{}} \DecValTok{20000} \SpecialCharTok{\textasciitilde{}} \StringTok{"Medio"}\NormalTok{,}
      \ConstantTok{TRUE} \SpecialCharTok{\textasciitilde{}} \StringTok{"Bajo"}
\NormalTok{    ),}
    \AttributeTok{categoria =} \FunctionTok{factor}\NormalTok{(categoria, }\AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Bajo"}\NormalTok{, }\StringTok{"Medio"}\NormalTok{, }\StringTok{"Alto"}\NormalTok{))}
\NormalTok{  )}

\CommentTok{\# Tabla resumen}
\NormalTok{tabla\_resumen }\OtherTok{\textless{}{-}}\NormalTok{ analisis\_rural\_urbano }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(categoria) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{n\_departamentos =} \FunctionTok{n}\NormalTok{(),}
    \AttributeTok{promedio\_tasa\_divorcio =} \FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(tasa\_divorcio\_por\_100), }\DecValTok{2}\NormalTok{),}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  )}

\FunctionTok{print}\NormalTok{(tabla\_resumen)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 3
##   categoria n_departamentos promedio_tasa_divorcio
##   <fct>               <int>                  <dbl>
## 1 Bajo                    2                  12.6 
## 2 Medio                  11                   7.64
## 3 Alto                    9                   6.12
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Gráfico de barras}
\FunctionTok{ggplot}\NormalTok{(tabla\_resumen, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ categoria, }\AttributeTok{y =}\NormalTok{ promedio\_tasa\_divorcio, }\AttributeTok{fill =}\NormalTok{ categoria)) }\SpecialCharTok{+}
  \FunctionTok{geom\_bar}\NormalTok{(}\AttributeTok{stat =} \StringTok{"identity"}\NormalTok{, }\AttributeTok{width =} \FloatTok{0.6}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_text}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{label =}\NormalTok{ promedio\_tasa\_divorcio), }
            \AttributeTok{vjust =} \SpecialCharTok{{-}}\FloatTok{0.5}\NormalTok{, }\AttributeTok{size =} \DecValTok{6}\NormalTok{, }\AttributeTok{fontface =} \StringTok{"bold"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}
    \AttributeTok{title =} \StringTok{"Tasa Promedio de Divorcio según Volumen de Matrimonios"}\NormalTok{,}
    \AttributeTok{subtitle =} \StringTok{"Guatemala 2009{-}2022"}\NormalTok{,}
    \AttributeTok{x =} \StringTok{"Volumen de Matrimonios del Departamento"}\NormalTok{,}
    \AttributeTok{y =} \StringTok{"Divorcios por cada 100 matrimonios"}
\NormalTok{  ) }\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{(}\AttributeTok{base\_size =} \DecValTok{14}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{scale\_fill\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"Bajo"} \OtherTok{=} \StringTok{"\#CD853F"}\NormalTok{, }\StringTok{"Medio"} \OtherTok{=} \StringTok{"\#DAA520"}\NormalTok{, }\StringTok{"Alto"} \OtherTok{=} \StringTok{"\#4169E1"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"none"}\NormalTok{,}
        \AttributeTok{plot.title =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{face =} \StringTok{"bold"}\NormalTok{, }\AttributeTok{size =} \DecValTok{16}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-21-1.pdf}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  ¿Sera que entre mas frios se tiende a tener una proporcion de
  divorcios mas bajos respecto al matrimonio?
\end{enumerate}

Al momento que llegamos a ver los clusters podemos ver una tendencia
curiosa, aquellos que estan en el cluster tres son departamentos frios
respecto a todos los demas.

Para eso podriamos juntar solo aquellos valores que son parte de estos
dos clusters, y viendo cuales son los valores mas bajos entre ellos y si
son considerados de lugares los cuales normalmente se consideran mas
frios en el pais de guatemala.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cluster\_data\_set }\OtherTok{=}\NormalTok{ depto\_clusters}

\NormalTok{cluster\_data\_set }\OtherTok{=}\NormalTok{ cluster\_data\_set[}\FunctionTok{order}\NormalTok{(cluster\_data\_set}\SpecialCharTok{$}\NormalTok{ratio\_div\_matr),]}

\NormalTok{ratio\_df }\OtherTok{=}\NormalTok{ cluster\_data\_set[}\FunctionTok{c}\NormalTok{(}\StringTok{"ratio\_div\_matr"}\NormalTok{, }\StringTok{"departamento"}\NormalTok{)]}

\NormalTok{ratio\_df}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 22 x 2
##    ratio_div_matr departamento 
##             <dbl> <chr>        
##  1         0.0258 alta verapaz 
##  2         0.0320 quiche       
##  3         0.0321 solola       
##  4         0.0327 chimaltenango
##  5         0.0342 huehuetenango
##  6         0.0354 totonicapan  
##  7         0.0452 san marcos   
##  8         0.0590 suchitepequez
##  9         0.0645 sacatepequez 
## 10         0.0661 peten        
## # i 12 more rows
\end{verbatim}

Aqui ya empezamos a mirar una tendencia, por ejemplo los 5 departamentos
con la proporcion de divorcios matrimonio son de lugares frios como Alta
Verapaz, Solola, Chimaltenango, Huehuetenango, Totonicapan y San Marcos.

Ahora lo que podemos hacerlo es separarlos en departamentos frios y
calientes solo entre 2 y el 3.

\begin{Shaded}
\begin{Highlighting}[]
  \CommentTok{\# Vector de departamentos fríos}
\NormalTok{departamentos\_frios }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"quiche"}\NormalTok{,}
                         \StringTok{"solola"}\NormalTok{,}
                         \StringTok{"chimaltenango"}\NormalTok{,}
                         \StringTok{"huehuetenango"}\NormalTok{,}
                         \StringTok{"totonicapan"}\NormalTok{,}
                         \StringTok{"quetzaltenango"}\NormalTok{,}
                         \StringTok{"san marcos"}\NormalTok{,}
                         \StringTok{"alta verapaz"}\NormalTok{,}
                         \StringTok{"baja verapaz"}\NormalTok{,}
                         \StringTok{"sacatepequez"}\NormalTok{)}

\NormalTok{dept\_frios }\OtherTok{=} \FunctionTok{filter}\NormalTok{(ratio\_df,departamento }\SpecialCharTok{\%in\%}\NormalTok{ departamentos\_frios)}

\NormalTok{resto\_depts }\OtherTok{=} \FunctionTok{filter}\NormalTok{(ratio\_df,}\SpecialCharTok{!}\NormalTok{departamento }\SpecialCharTok{\%in\%}\NormalTok{ departamentos\_frios)}

\NormalTok{dept\_frios}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 10 x 2
##    ratio_div_matr departamento  
##             <dbl> <chr>         
##  1         0.0258 alta verapaz  
##  2         0.0320 quiche        
##  3         0.0321 solola        
##  4         0.0327 chimaltenango 
##  5         0.0342 huehuetenango 
##  6         0.0354 totonicapan   
##  7         0.0452 san marcos    
##  8         0.0645 sacatepequez  
##  9         0.0706 baja verapaz  
## 10         0.0996 quetzaltenango
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{resto\_depts}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 12 x 2
##    ratio_div_matr departamento 
##             <dbl> <chr>        
##  1         0.0590 suchitepequez
##  2         0.0661 peten        
##  3         0.0739 escuintla    
##  4         0.0891 chiquimula   
##  5         0.0902 santa rosa   
##  6         0.0917 retalhuleu   
##  7         0.0923 jutiapa      
##  8         0.102  jalapa       
##  9         0.107  izabal       
## 10         0.124  zacapa       
## 11         0.127  el progreso  
## 12         0.149  guatemala
\end{verbatim}

Ahora que ya tenemos los dos grupos separados, ahora `plotemos' estos
valores uno encima de otro, para ver cua de los dos grupos tienden a
tener una proporcion de divorcios respecto a matrimonios mejor (mas
bajo).osea

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datos }\OtherTok{\textless{}{-}} \FunctionTok{rbind}\NormalTok{(}
  \AttributeTok{Resto =}\NormalTok{ resto\_depts}\SpecialCharTok{$}\NormalTok{ratio\_div\_matr,}
  \AttributeTok{Frios =}\NormalTok{ dept\_frios}\SpecialCharTok{$}\NormalTok{ratio\_div\_matr}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in rbind(Resto = resto_depts$ratio_div_matr, Frios =
## dept_frios$ratio_div_matr): number of columns of result is not a multiple of
## vector length (arg 2)
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{barplot}\NormalTok{(}
\NormalTok{  resto\_depts}\SpecialCharTok{$}\NormalTok{ratio\_div\_matr,}
  \AttributeTok{col =} \StringTok{"orange"}\NormalTok{,}
  \AttributeTok{xlab =} \StringTok{"Departamentos"}\NormalTok{,}
  \AttributeTok{ylab =} \StringTok{"Proporcion de divorcios por matrimonios"}\NormalTok{,}
  \AttributeTok{legend.text =} \ConstantTok{TRUE}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-24-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{barplot}\NormalTok{(}
\NormalTok{  dept\_frios}\SpecialCharTok{$}\NormalTok{ratio\_div\_matr,}
  \AttributeTok{col =} \StringTok{"blue"}\NormalTok{,}
  \AttributeTok{xlab =} \StringTok{"Departamentos"}\NormalTok{,}
  \AttributeTok{ylab =} \StringTok{"Proporcion de divorcios por matrimonios"}\NormalTok{,}
  \AttributeTok{legend.text =} \ConstantTok{TRUE}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-24-2.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{barplot}\NormalTok{(}
\NormalTok{  datos,}
  \AttributeTok{beside =} \ConstantTok{TRUE}\NormalTok{,}
  \AttributeTok{col =} \FunctionTok{c}\NormalTok{(}\StringTok{"orange"}\NormalTok{, }\StringTok{"blue"}\NormalTok{),}
  \AttributeTok{xlab =} \StringTok{"Departamentos"}\NormalTok{,}
  \AttributeTok{ylab =} \StringTok{"Proporcion de divorcios por matrimonios"}\NormalTok{,}
  \AttributeTok{legend.text =} \ConstantTok{TRUE}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-24-3.pdf}}

Como podemos llegar a ver si llega a ver esa tendencia, quitando la
capital los departamentos mas frios tienden a tener una proporcion de
divorcios por matrimonios bastante menor.

Para poder respaldar aun mas lo visto, probemos ver si estos valores
tambien se mantienen entre los meses mas frios.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{matrimonios\_mensual }\OtherTok{\textless{}{-}}\NormalTok{ matrimonios\_depto }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}
\NormalTok{    nivel\_geo }\SpecialCharTok{==} \StringTok{"departamento"}\NormalTok{,}
\NormalTok{    departamento }\SpecialCharTok{!=} \StringTok{"guatemala"}\NormalTok{,}
    \SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(mes),}
    \SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(departamento)}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{departamento =} \FunctionTok{norm\_depto}\NormalTok{(departamento)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(mes, departamento) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{matrimonios =} \FunctionTok{sum}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{)}

\NormalTok{divorcios\_mensual }\OtherTok{\textless{}{-}}\NormalTok{ divorcios\_depto }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{filter}\NormalTok{(}
\NormalTok{    nivel\_geo }\SpecialCharTok{==} \StringTok{"departamento"}\NormalTok{,}
\NormalTok{    departamento }\SpecialCharTok{!=} \StringTok{"guatemala"}\NormalTok{,}
    \SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(mes),}
    \SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(departamento)}
\NormalTok{  ) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{departamento =} \FunctionTok{norm\_depto}\NormalTok{(departamento)) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(mes, departamento) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}\AttributeTok{divorcios =} \FunctionTok{sum}\NormalTok{(valor, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{)}


\NormalTok{matrimonios\_divorcios\_depto\_mes }\OtherTok{\textless{}{-}} \FunctionTok{full\_join}\NormalTok{(}
\NormalTok{  matrimonios\_mensual,}
\NormalTok{  divorcios\_mensual,}
  \AttributeTok{by =} \FunctionTok{c}\NormalTok{(}\StringTok{"mes"}\NormalTok{)}
\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}
    \AttributeTok{ratio\_div\_matr =}\NormalTok{ divorcios }\SpecialCharTok{/}\NormalTok{ matrimonios}
\NormalTok{  )}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in full_join(matrimonios_mensual, divorcios_mensual, by = c("mes")): Detected an unexpected many-to-many relationship between `x` and `y`.
## i Row 1 of `x` matches multiple rows in `y`.
## i Row 1 of `y` matches multiple rows in `x`.
## i If a many-to-many relationship is expected, set `relationship =
##   "many-to-many"` to silence this warning.
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mes\_stats }\OtherTok{\textless{}{-}}\NormalTok{ matrimonios\_divorcios\_depto\_mes }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{group\_by}\NormalTok{(mes) }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{summarise}\NormalTok{(}
    \AttributeTok{avg\_matrimonios =} \FunctionTok{mean}\NormalTok{(matrimonios, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{avg\_divorcios   =} \FunctionTok{mean}\NormalTok{(divorcios, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{),}
    \AttributeTok{ratio\_div\_matr  =}\NormalTok{ avg\_divorcios }\SpecialCharTok{/}\NormalTok{ avg\_matrimonios,}
    \AttributeTok{.groups =} \StringTok{"drop"}
\NormalTok{  )}


\NormalTok{ratio\_df\_mes }\OtherTok{=}\NormalTok{ mes\_stats[}\FunctionTok{c}\NormalTok{(}\StringTok{"ratio\_div\_matr"}\NormalTok{, }\StringTok{"mes"}\NormalTok{)]}

\NormalTok{ratio\_df\_mes}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 12 x 2
##    ratio_div_matr   mes
##             <dbl> <dbl>
##  1         0.0515     1
##  2         0.0589     2
##  3         0.0579     3
##  4         0.0543     4
##  5         0.0573     5
##  6         0.0699     6
##  7         0.0651     7
##  8         0.0658     8
##  9         0.0700     9
## 10         0.0726    10
## 11         0.0621    11
## 12         0.0467    12
\end{verbatim}

Aqui estamos segmentando el data set por meses, pero quitando el gran
outlier de la capital.

\begin{Shaded}
\begin{Highlighting}[]
  \CommentTok{\# Vector de departamentos fríos}
\NormalTok{meses\_frios\_list }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{11}\NormalTok{,}\DecValTok{12}\NormalTok{,}\DecValTok{1}\NormalTok{)}

\NormalTok{meses\_frios }\OtherTok{=} \FunctionTok{filter}\NormalTok{(ratio\_df\_mes,mes }\SpecialCharTok{\%in\%}\NormalTok{ meses\_frios\_list)}

\NormalTok{resto\_meses }\OtherTok{=} \FunctionTok{filter}\NormalTok{(ratio\_df\_mes,}\SpecialCharTok{!}\NormalTok{mes }\SpecialCharTok{\%in\%}\NormalTok{ meses\_frios\_list)}

\NormalTok{meses\_frios}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 3 x 2
##   ratio_div_matr   mes
##            <dbl> <dbl>
## 1         0.0515     1
## 2         0.0621    11
## 3         0.0467    12
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{resto\_meses}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 9 x 2
##   ratio_div_matr   mes
##            <dbl> <dbl>
## 1         0.0589     2
## 2         0.0579     3
## 3         0.0543     4
## 4         0.0573     5
## 5         0.0699     6
## 6         0.0651     7
## 7         0.0658     8
## 8         0.0700     9
## 9         0.0726    10
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datos }\OtherTok{\textless{}{-}} \FunctionTok{rbind}\NormalTok{(}
  \AttributeTok{Resto =}\NormalTok{ resto\_meses}\SpecialCharTok{$}\NormalTok{ratio\_div\_matr,}
  \AttributeTok{Frios =}\NormalTok{ meses\_frios}\SpecialCharTok{$}\NormalTok{ratio\_div\_matr}
\NormalTok{)}

\FunctionTok{barplot}\NormalTok{(}
\NormalTok{  resto\_meses}\SpecialCharTok{$}\NormalTok{ratio\_div\_matr,}
  \AttributeTok{col =} \StringTok{"orange"}\NormalTok{,}
  \AttributeTok{names.arg =}\NormalTok{ resto\_meses}\SpecialCharTok{$}\NormalTok{mes,}
  \AttributeTok{xlab =} \StringTok{"Meses"}\NormalTok{,}
  \AttributeTok{ylab =} \StringTok{"Proporcion de divorcios por matrimonios"}\NormalTok{,}
  \AttributeTok{legend.text =} \ConstantTok{TRUE}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-27-1.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{barplot}\NormalTok{(}
\NormalTok{  meses\_frios}\SpecialCharTok{$}\NormalTok{ratio\_div\_matr,}
  \AttributeTok{col =} \StringTok{"blue"}\NormalTok{,}
  \AttributeTok{names.arg =}\NormalTok{ meses\_frios}\SpecialCharTok{$}\NormalTok{mes,}
  \AttributeTok{xlab =} \StringTok{"Meses"}\NormalTok{,}
  \AttributeTok{ylab =} \StringTok{"Proporcion de divorcios por matrimonios"}\NormalTok{,}
  \AttributeTok{legend.text =} \ConstantTok{TRUE}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Analisis_files/figure-latex/unnamed-chunk-27-2.pdf}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(meses\_frios}\SpecialCharTok{$}\NormalTok{ratio\_div\_matr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.05343807
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mean}\NormalTok{(resto\_meses}\SpecialCharTok{$}\NormalTok{ratio\_div\_matr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.06353211
\end{verbatim}

Aqui podemos ver que en proporcion a la pura temperatura no llega a ser
tan notable, tambien estamos aqui combinando todos los departamentos, lo
cual tambien pueda darnos la idea que normalmente los departamentos que
tienden a climas mas frios tambien tienen otros factores probablemente
culturales que cambian esta metrica.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{\texorpdfstring{\textbf{Hallazgos y
Conclusiones}}{Hallazgos y Conclusiones}}\label{hallazgos-y-conclusiones}

\subsubsection{\texorpdfstring{\textbf{Resumen de Hallazgos en Análisis
Exploratorio}}{Resumen de Hallazgos en Análisis Exploratorio}}\label{resumen-de-hallazgos-en-anuxe1lisis-exploratorio}

\textbf{Estructura del Conjunto de Datos}

\begin{itemize}
\tightlist
\item
  Se trabajó con 4 datasets (2009--2022): matrimonios por
  departamento/mes, matrimonios por rangos de edad, divorcios por
  departamento/mes y divorcios por rangos de edad.
\item
  Cada dataset contiene una variable clave de conteo (valor) que
  representa la cantidad de eventos (matrimonios o divorcios) para una
  combinación de variables categóricas (año/mes/departamento/edad).
\end{itemize}

\textbf{Variables Cuantitativas}

\begin{itemize}
\tightlist
\item
  Se analizó principalmente valor, ya que las demás variables numéricas
  (año/mes) funcionan como identificadores temporales y no como
  magnitudes interpretables para tendencia central/dispersión.
\item
  En general, valor muestra asimetría positiva (media \textgreater{}
  mediana) y presencia de valores atípicos, especialmente en
  departamentos con mayor concentración poblacional.
\end{itemize}

\textbf{Distribución y Normalidad}

\begin{itemize}
\tightlist
\item
  Los histogramas y boxplots muestran concentración de valores bajos con
  colas largas (outliers) en los cuatro datasets.
\item
  La prueba de Lilliefors rechaza normalidad para valor en los datasets
  analizados (p-value \textless{} 0), confirmando que no siguen
  distribución normal.
\end{itemize}

\textbf{Variables Cualitativas}

\begin{itemize}
\tightlist
\item
  Por departamento, Guatemala domina tanto en matrimonios como
  divorcios, mostrando una diferencia marcada frente al resto.
\item
  Los matrimonios se concentran principalmente en edades jóvenes adultas
  (por ejemplo, 20--24 y 25--29).
\item
  Los divorcios tienden a concentrarse en rangos más altos que los
  matrimonios (por ejemplo, 25--29, 30--34 y 35--39, dependiendo del
  sexo).
\end{itemize}

\textbf{Relaciones entre variables}

\begin{itemize}
\tightlist
\item
  En el análisis por edades (gráfico de burbujas), se observan
  concentraciones fuertes en combinaciones específicas de edades
\item
  La relación entre total anual de matrimonios y divorcios muestra una
  correlación positiva moderada (≈ 0.60): cuando hay más matrimonios en
  un año, también suelen registrarse más divorcios, aunque con
  variabilidad.
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection{\texorpdfstring{\textbf{Resumen de
Clustering}}{Resumen de Clustering}}\label{resumen-de-clustering}

\textbf{Cluster 1 --- ``Outlier (Guatemala)''}

\begin{itemize}
\tightlist
\item
  Característica principal: promedios de matrimonios y divorcios muy
  superiores al resto, y ratio relativamente alto.
\end{itemize}

\textbf{Cluster 2 --- ``Alta proporción de divorcios''}

\begin{itemize}
\tightlist
\item
  Característica principal: ratio divorcios/matrimonios medio--alto
  (aprox. 0.065 a 0.127).
\end{itemize}

\textbf{Cluster 3 --- ``Baja proporción de divorcios''} - Característica
principal: ratio divorcios/matrimonios bajo (menor a
\textasciitilde0.059), aunque algunos tienen altos promedios de
matrimonios.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection{\texorpdfstring{\textbf{Conclusiones con Base a
Objetivos}}{Conclusiones con Base a Objetivos}}\label{conclusiones-con-base-a-objetivos}

\textbf{Analizar los datos de matrimonios y divorcios en Guatemala para
identificar patrones demográficos, diferencias entre departamentos y
cambios en la dinámica a lo largo del período.}

\begin{itemize}
\item
  El análisis exploratorio muestra patrones claros de concentración
  tanto por edad como por departamento, por lo que sí existen
  diferencias relevantes entre regiones y grupos etarios.
\item
  A nivel temporal, los datos sugieren variaciones en la dinámica de
  divorcios al comparar periodos (por ejemplo, 2019--2022 vs
  2009--2012), lo cual es consistente con la hipótesis de cambios
  sociales en años recientes.
\item
  En la relación global, se observó una asociación moderada entre
  matrimonios y divorcios, en años con más matrimonios, tienden a
  registrarse más divorcios, aunque con variabilidad.
\end{itemize}

\textbf{Analizar los datos de matrimonios y divorcios en Guatemala para
identificar patrones demográficos, diferencias entre departamentos y
cambios en la dinámica a lo largo del período.}

\begin{itemize}
\item
  El análisis exploratorio muestra patrones claros de concentración
  tanto por edad como por departamento, por lo que sí existen
  diferencias relevantes entre regiones y grupos etarios.
\item
  A nivel temporal, los datos sugieren variaciones en la dinámica de
  divorcios al comparar periodos (por ejemplo, 2019--2022 vs
  2009--2012), lo cual es consistente con la hipótesis de
  \textbf{cambios sociales} en años recientes.
\item
  En la relación global, se observó una asociación moderada entre
  matrimonios y divorcios, en años con más matrimonios, tienden a
  registrarse más divorcios, aunque con variabilidad.
\end{itemize}

\textbf{Examinar la distribución de matrimonios y divorcios según rangos
de edad, identificando variaciones en las edades donde ocurren estos
eventos.}

\begin{itemize}
\item
  Los matrimonios no se distribuyen uniformemente entre rangos de edad:
  se concentran en rangos específicos (por ejemplo, en el análisis de
  frecuencias, los mayores registros se ubican en edades jóvenes-adultas
  como 20--24 y 25--29).
\item
  Los divorcios tienden a concentrarse en rangos mayores respecto a los
  matrimonios (por ejemplo, rangos como 25--29, 30--34 y 35--39 aparecen
  con alta presencia), lo que sugiere que el divorcio ocurre con mayor
  frecuencia después de algunos años de vida en pareja.
\end{itemize}

\textbf{Analizar la distribución de matrimonios y divorcios por
departamento para detectar patrones regionales relevantes.}

\begin{itemize}
\item
  Existe una concentración fuerte de eventos en el departamento de
  Guatemala, que destaca ampliamente tanto en matrimonios como en
  divorcios (y por proporciones, especialmente en divorcios).
\item
  Al comparar ``capital vs interior'', la tasa promedio de divorcios por
  cada 100 matrimonios fue mayor en Guatemala (≈ 14.87) que en el resto
  del país (≈ 6.03), confirmando diferencias regionales relevantes.
\item
  El clustering reforzó la existencia de patrones departamentales:

  \begin{itemize}
  \tightlist
  \item
    Guatemala se comporta como caso atípico.
  \end{itemize}
\end{itemize}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsubsection{\texorpdfstring{\textbf{Potencial Plan de Pasos a
Seguir}}{Potencial Plan de Pasos a Seguir}}\label{potencial-plan-de-pasos-a-seguir}

Tras analizar los patrones de matrimonios y divorcios en Guatemala
(2009--2022) a nivel geográfico y demográfico, se identificó que el
departamento de Guatemala presenta un comportamiento marcadamente
distinto al resto. Por ello, un siguiente paso sería profundizar su
análisis y formular hipótesis explicativas (por ejemplo, diferencias en
urbanización, acceso a servicios legales, concentración económica, etc),
para luego contrastarlas con evidencia adicional.

En cuanto a los matrimonios, los registros se concentran principalmente
en el rango de 20 a 30 años, por lo que conviene explorar con más
detalle si esta concentración tiene factores económicos detrás, como que
la mayoría de personas empiezan a laburar en esta rango, o si existen
más factores.

Respecto a los divorcios, sería relevante analizar su evolución en años
recientes más a fondo, con el fin de comprender qué cambios culturales
han ocurrido que hagan que se presente este fenómeno.

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\end{document}
